name = "polyhedral-example"
cuda_devices = "0"
plotting_points = 2500
ground_truth = [
    "polyhedral",
    "mascon"
]
samples = [
    "Churyumov-Gerasimenko"
]
noise = [

]

[model]
activation = [
    "Abs"
]
encoding = [
    "direct_encoding"
]
use_acceleration = true
type = "siren"
hidden_layers = [
    3
]
n_neurons = [
    100
]

[siren]
omega = [
    30.0
]

[integration]
points = 10
limit_domain = false
domain = [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]]

[training]
iterations = 500
batch_size = [
    100
]
learning_rate =[
    1e-4
]
loss = [
    "normalized_L1_loss"
]
validation_points = 1000
validation_ground_truth = "polyhedral"
validation_sampling_altitudes = [0.05, 0.1, 0.25]

[target_sampling]
method = [
    "spherical"
]
domain = [
    [0.0, 1.0]
]
