name = "polyhedral-example"
cuda_devices = "0"
plotting_points = 2500
ground_truth = [
    "polyhedral",
    "mascon"
]
samples = [
    "churyumov-gerasimenko"
]
noise = [

]

[model]
activation = [
    "Abs",
    "Sigmoid"
]
encoding = [
    "direct_encoding",
    "spherical_coordinates"
]
use_acceleration = true
type = "siren"
hidden_layers = [
    9
]
n_neurons = [
    100
]

[siren]
omega = [
    30.0
]

[integration]
points = 300000
limit_domain = false
domain = [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]]

[training]
iterations = 10000
batch_size = [
    1000
]
learning_rate =[
    1e-4
]
loss = [
    "normalized_L1_loss"
]
validation_points = 1000
validation_ground_truth = "polyhedral"
validation_sampling_altitudes = [1e-5, 1e-3, 1e-1]

[target_sampling]
method = [
    "spherical"
]
domain = [
    [0.0, 1.0],
    [1.0, 2.0]
]
