name: geodesynet
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - ipython
  - scikit-learn
  - numpy
  - matplotlib
  - jupyter
  - tqdm>=4.50.0
  - pandas
  - polyhedral-gravity-model
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - pytest
  - pytest-xdist
  - toml
  - seaborn
  - pip
  - pip:
      - sobol_seq
      - pyvista
      - pyvistaqt