name = "short-cg-0010"
cuda_devices = "3"
plotting_points = 2500
seed = [
    3, 7, 9, 37, 42, 67, 99, 433, 1999, 2023
]
resolution = "100%"
ground_truth = [
    "polyhedral",
]
samples = [
    "churyumov-gerasimenko"
]
noise = [
    [""],
    ["gaussian", 0.0, 0.146731],
    ["gaussian", 0.0, 1.467314],
    ["constant_bias", [0.000272, 0.0, 0.0]],
    ["adaptive_gaussian_noise", 0.1],
    ["adaptive_gaussian_noise", 0.01],
    ["adaptive_gaussian_noise", 0.001]
]
[model]
activation = [
    "Abs"
]
encoding = [
    "direct_encoding"
]
use_acceleration = true
type = "siren"
hidden_layers = [
    9
]
n_neurons = [
    100
]

[siren]
omega = [
    30.0
]

[integration]
points = 300000
limit_domain = false
domain = [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]]

[training]
iterations = [10, 100]
batch_size = [
    1000
]
learning_rate = [
    1e-4
]
loss = [
    "normalized_L1_loss"
]
validation_points = 1000
validation_ground_truth = "polyhedral"
validation_sampling_altitudes = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0, 50.0]

[target_sampling]
method = [
    "spherical"
]
domain = [
    [3.0, 5.0]
]